#################
#VoidHUB
#By CookieCode
#Contact me on twitter if you have any problem (@ImCookieGame)
#################

#teleport_hub_message : Change the message when the plugin teleported you to the hub
teleport_hub_message: "§eYou've been teleported to the hub !"
